ignoreProblematicDevices property added
Banno/Gordon pull request #99
Opened 2021-05-23 18:26 UTC by grzechu92

### :pushpin: References

* Related to #84

### :goal_net: What is the goal?

* When there is a lot of devices/emulators available sometimes it's worth to just proceed with for example 34/35 emulators instead of failing whole build.

### :computer: How is it implemented?

* Didn't know anything about Arrow Fx, I hope that I nailed it! :hammer: 
* I'm wondering if it's better to keep `List<DevicePool>` or change it to `Mutable<DevicePool>` and modify it once instead filtering before each `pools` usage
* I tested it by adding `Thread.sleep(10000)` before installation steps and killing emulator when it tries to install application/instruemntation. It proceeds without any issues.
* Since all devices in the pool may fail, in that case test should (:question:) fail, validation for that case is added as well.

2021-05-24 14:21 UTC, joshschriever requested changes
Looks pretty good overall, thanks for the contribution! Just several relatively minor suggestions.

2021-05-24 14:21 UTC, joshschriever commented on gordon-plugin/src/main/kotlin/com/banno/gordon/AdbExtensions.kt
> +internal fun Either<Throwable, Unit>.ignoreErrorIfPossible(
```suggestion
private fun Either<Throwable, Unit>.ignoreErrorIfPossible(
```

2021-05-24 14:21 UTC, joshschriever commented on gordon-plugin/src/main/kotlin/com/banno/gordon/AdbExtensions.kt
> +    }
A couple things here:
- I think this would be a more idiomatic way to write the same thing with Arrow
- I think `logger.warn` would be more appropriate here than `lifecycle`

```suggestion
): Either<Throwable, Unit> = fold(
    ifLeft = {
        Either.conditionally(ignoreProblematicDevices, ifFalse = { it }) {
            problematicDevices.add(device)
            logger.warn("${device.serialNumber}: ignored installation failure", it)
        }
    },
    ifRight = { it.right() }
)
```

2021-05-24 14:21 UTC, joshschriever commented on gordon-plugin/src/main/kotlin/com/banno/gordon/GordonTestTask.kt
> +    internal val ignoreProblematicDevices: Property<Boolean> = objects.property()
I think this should be internal. When any property marked as an input changes, the task has to rerun. Think of this case: If, after a successful test run, the only change made is to the `ignoreProblematicDevices` property, I don't think the task should rerun because it doesn't affect the tests themselves.

```suggestion
    @get:Internal
    internal val ignoreProblematicDevices: Property<Boolean> = objects.property()
```

2021-05-24 14:21 UTC, joshschriever commented on gordon-plugin/src/main/kotlin/com/banno/gordon/GordonTestTask.kt
> +            var pools = calculatePools(
```suggestion
            val originalPools = calculatePools(
```

2021-05-24 14:21 UTC, joshschriever commented on gordon-plugin/src/main/kotlin/com/banno/gordon/GordonTestTask.kt
> +            pools.validateDevicePools().bind()
```suggestion
            originalPools.validateDevicePools().bind()
```

2021-05-24 14:21 UTC, joshschriever commented on gordon-plugin/src/main/kotlin/com/banno/gordon/GordonTestTask.kt
> +            pools = pools.filterProblematicDevices(problematicDevices)
```suggestion
            val pools = originalPools.filterProblematicDevices(problematicDevices)
```

2021-05-24 14:21 UTC, joshschriever commented on gordon-plugin/src/main/kotlin/com/banno/gordon/GordonTestTask.kt
> +                allPools = pools.filterProblematicDevices(problematicDevices),
`pools` would already be filtered at this point, so we don't need to do it again, do we?

```suggestion
                allPools = pools,
```

2021-05-24 14:21 UTC, joshschriever commented on gordon-plugin/src/main/kotlin/com/banno/gordon/GordonTestTask.kt
> +            pools.filterProblematicDevices(problematicDevices).flatMap { it.devices }.safeUninstall(
`safeUninstall` already ignores failures, so we might as well try to do as much cleanup as possible and try it on all devices

```suggestion
            originalPools.flatMap { it.devices }.safeUninstall(
```

2021-05-24 14:21 UTC, joshschriever commented on gordon-plugin/src/main/kotlin/com/banno/gordon/GordonTestTask.kt
> +    }
```suggestion
    map { pool ->
        pool.copy(devices = pool.devices - problematicDevices)
    }
```

2021-08-24 13:55 UTC, joshschriever approved these changes

2021-08-24 16:18 UTC, chrisHoekstra approved these changes

2021-08-24 16:20 UTC, merged

2021-08-25 06:18 UTC, grzechu92 commented
Thank you for instant release with that change, and really sorry for the PR delay :heart: